name: Bug Report
description: Report a bug in the EFY Frontend platform
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        
        Before creating a bug report, please check:
        - [ ] The issue is not already reported in existing issues
        - [ ] The issue is not a duplicate of another issue
        - [ ] You have the latest version of the code
        - [ ] The issue is reproducible

  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Frontend UI/UX Issue
        - API Integration Issue
        - Authentication/Authorization Issue
        - Performance Issue
        - Browser Compatibility Issue
        - Mobile/Responsive Issue
        - Data Loading/Display Issue
        - Form Validation Issue
        - State Management Issue
        - Build/Deployment Issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable, data loss, security issue
        - High - Major functionality broken, workaround available
        - Medium - Minor functionality broken, workaround available
        - Low - Cosmetic issue, minor inconvenience
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did you encounter this bug?
      options:
        - Production
        - Staging
        - Development
        - Local Development
        - All Environments
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser and version are you using?
      placeholder: "Chrome 120.0.6099.109, Firefox 121.0, Safari 17.1, Edge 120.0.2210.91"
    validations:
      required: false

  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using?
      placeholder: "Desktop, iPhone 15, Samsung Galaxy S23, iPad Pro"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Windows 11, macOS 14.1, Ubuntu 22.04, iOS 17.1, Android 14"
    validations:
      required: false

  - type: input
    id: issue_title
    attributes:
      label: Brief Description
      description: Provide a concise summary of the bug
      placeholder: "User profile page shows blank screen after login"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the bug
      placeholder: |
        ## What happened?
        Describe the bug in detail...
        
        ## What did you expect to happen?
        Describe what you expected to happen instead...
        
        ## Steps to reproduce
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
        
        ## Additional context
        Any other context about the problem...
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps to reproduce the bug
      placeholder: |
        1. Navigate to the login page
        2. Enter valid credentials
        3. Click "Sign In" button
        4. Observe that the user profile page loads blank
        
        **Note:** Include any specific data, settings, or conditions that trigger the bug.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: |
        - The user profile page should display user information
        - The page should load within 3 seconds
        - All user data should be visible and editable
        - No error messages should appear
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        - The user profile page shows a blank white screen
        - The page takes 10+ seconds to load
        - Console shows JavaScript errors
        - User data is not displayed
    validations:
      required: true

  - type: textarea
    id: console_errors
    attributes:
      label: Console Errors
      description: Include any JavaScript console errors or warnings
      placeholder: |
        ```
        Error: Failed to fetch user data
        TypeError: Cannot read property 'name' of undefined
        Warning: React Hook useEffect has a missing dependency
        ```
    validations:
      required: false

  - type: textarea
    id: network_errors
    attributes:
      label: Network Errors
      description: Include any network request failures or API errors
      placeholder: |
        ```
        GET /api/user/profile 500 Internal Server Error
        POST /api/auth/login 401 Unauthorized
        CORS error: Access to fetch at '...' from origin '...' has been blocked
        ```
    validations:
      required: false

  - type: textarea
    id: user_data
    attributes:
      label: User Data Context
      description: Include relevant user data or account information (without sensitive details)
      placeholder: |
        - User role: Admin/User/Guest
        - Account type: Free/Premium
        - Data being accessed: Profile settings, Dashboard, Reports
        - Recent actions: Login, Password change, Profile update
        
        **Note:** Do not include passwords, API keys, or other sensitive information.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Include screenshots or screen recordings if applicable
      placeholder: |
        - Screenshot of the error page
        - Screenshot of the console errors
        - Video showing the reproduction steps
        - Screenshot of the network tab showing failed requests
        
        **Note:** You can drag and drop images directly into this field.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Does this happen with all users or specific accounts?
        - Does this happen in all browsers or specific ones?
        - Is this a regression (worked before)?
        - Any recent changes that might have caused this?
        - Related to specific features or pages?
    validations:
      required: false

  - type: checkboxes
    id: bug_characteristics
    attributes:
      label: Bug Characteristics
      description: Check any items that apply to this bug
      options:
        - label: This bug is reproducible consistently
        - label: This bug is intermittent/random
        - label: This bug affects all users
        - label: This bug affects specific user types
        - label: This bug is a regression (worked before)
        - label: This bug is related to authentication
        - label: This bug is related to data loading
        - label: This bug is related to form submission
        - label: This bug is related to API integration
        - label: This bug is related to AWS Lambda backend
        - label: This bug is related to performance
        - label: This bug is related to mobile/responsive design

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Link any related issues or pull requests
      placeholder: "Fixes #123, Related to #456, Duplicate of #789"
    validations:
      required: false

  - type: input
    id: labels
    attributes:
      label: Additional Labels
      description: Add any additional labels that might be relevant
      placeholder: "frontend, api, auth, performance, mobile, etc."
    validations:
      required: false