name: Feature Request
description: Suggest a new feature or enhancement for the EFY Frontend platform
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request
        
        Before creating a feature request, please check:
        - [ ] The feature is not already implemented
        - [ ] The feature is not already requested in existing issues
        - [ ] The feature aligns with the project's goals and scope
        - [ ] You have a clear understanding of the problem being solved

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - New Page/Component
        - API Integration
        - Authentication Feature
        - Data Visualization
        - Performance Optimization
        - Mobile/Responsive Feature
        - Accessibility Feature
        - Internationalization
        - Analytics/Reporting
        - Integration with AWS Services
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Essential for core functionality
        - High - Important for user experience
        - Medium - Nice to have improvement
        - Low - Future enhancement
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: User Impact
      description: Who will benefit from this feature?
      options:
        - All Users
        - Admin Users Only
        - Premium Users Only
        - Specific User Groups
        - Internal Team
        - External Integrations
    validations:
      required: true

  - type: input
    id: issue_title
    attributes:
      label: Feature Title
      description: Provide a concise summary of the feature request
      placeholder: "Add dark mode theme support"
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: |
        ## What problem does this feature solve?
        
        Currently, users struggle with [describe the problem]...
        
        This causes issues such as:
        - [Issue 1]
        - [Issue 2]
        - [Issue 3]
        
        ## Why is this problem important?
        
        [Explain the impact and why it matters to users]
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: |
        ## Proposed Solution
        
        I suggest implementing [describe the feature] that would:
        
        - [Benefit 1]
        - [Benefit 2]
        - [Benefit 3]
        
        ## How it would work
        
        [Describe the user flow and technical approach]
        
        ## Key Features
        
        - [Feature 1]
        - [Feature 2]
        - [Feature 3]
    validations:
      required: true

  - type: textarea
    id: user_stories
    attributes:
      label: User Stories
      description: Describe the user stories for this feature
      placeholder: |
        ## User Stories
        
        As a [user type], I want to [action] so that [benefit].
        
        ### Examples:
        - As a user, I want to toggle between light and dark themes so that I can use the app comfortably in different lighting conditions.
        - As an admin, I want to view user analytics so that I can understand platform usage patterns.
        - As a developer, I want to integrate with AWS Lambda functions so that I can extend functionality.
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define clear acceptance criteria for this feature
      placeholder: |
        ## Acceptance Criteria
        
        ### Functional Requirements
        - [ ] [Criterion 1]
        - [ ] [Criterion 2]
        - [ ] [Criterion 3]
        
        ### Non-Functional Requirements
        - [ ] Performance: [specific requirement]
        - [ ] Accessibility: [specific requirement]
        - [ ] Security: [specific requirement]
        - [ ] Browser Compatibility: [specific requirement]
        
        ### Technical Requirements
        - [ ] [Technical requirement 1]
        - [ ] [Technical requirement 2]
        - [ ] [Technical requirement 3]
    validations:
      required: false

  - type: textarea
    id: mockups_designs
    attributes:
      label: Mockups/Designs
      description: Include any mockups, wireframes, or design references
      placeholder: |
        ## Design References
        
        - Wireframes: [link to wireframes]
        - Mockups: [link to mockups]
        - Design system references: [link to design system]
        - Similar features in other apps: [examples]
        
        **Note:** You can drag and drop images directly into this field.
    validations:
      required: false

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Describe any technical considerations or requirements
      placeholder: |
        ## Technical Considerations
        
        ### Frontend Requirements
        - React components needed: [list]
        - State management: [requirements]
        - API integration: [requirements]
        - Performance considerations: [requirements]
        
        ### Backend Requirements
        - AWS Lambda functions: [requirements]
        - Database changes: [requirements]
        - API endpoints: [requirements]
        - Authentication: [requirements]
        
        ### Integration Points
        - Third-party services: [list]
        - AWS services: [list]
        - External APIs: [list]
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered
      placeholder: |
        ## Alternatives Considered
        
        ### Alternative 1: [Brief description]
        - Pros: [list]
        - Cons: [list]
        - Why rejected: [reason]
        
        ### Alternative 2: [Brief description]
        - Pros: [list]
        - Cons: [list]
        - Why rejected: [reason]
    validations:
      required: false

  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation Plan (Optional)
      description: If you have ideas for implementation, describe them here
      placeholder: |
        ## Implementation Plan
        
        ### Phase 1: [Description]
        - [Task 1]
        - [Task 2]
        - [Task 3]
        
        ### Phase 2: [Description]
        - [Task 1]
        - [Task 2]
        - [Task 3]
        
        ### Timeline Estimate
        - Development time: [estimate]
        - Testing time: [estimate]
        - Documentation time: [estimate]
    validations:
      required: false

  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics
      description: How will we measure the success of this feature?
      placeholder: |
        ## Success Metrics
        
        ### Quantitative Metrics
        - User adoption rate: [target]
        - Performance improvement: [target]
        - Error rate reduction: [target]
        - User satisfaction score: [target]
        
        ### Qualitative Metrics
        - User feedback: [how to measure]
        - Usability improvements: [how to measure]
        - Accessibility improvements: [how to measure]
    validations:
      required: false

  - type: checkboxes
    id: feature_characteristics
    attributes:
      label: Feature Characteristics
      description: Check any items that apply to this feature request
      options:
        - label: This feature improves user experience
        - label: This feature improves performance
        - label: This feature enhances security
        - label: This feature improves accessibility
        - label: This feature integrates with AWS services
        - label: This feature requires backend changes
        - label: This feature requires database changes
        - label: This feature requires API changes
        - label: This feature is mobile-responsive
        - label: This feature supports internationalization
        - label: This feature includes analytics/reporting
        - label: This feature requires third-party integration

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Link any related issues or pull requests
      placeholder: "Related to #123, Depends on #456, Blocks #789"
    validations:
      required: false

  - type: input
    id: labels
    attributes:
      label: Additional Labels
      description: Add any additional labels that might be relevant
      placeholder: "ui/ux, api, aws, mobile, accessibility, etc."
    validations:
      required: false