name: Infrastructure Issue
description: Report issues with AWS infrastructure, deployment, or backend services
title: "[INFRASTRUCTURE] "
labels: ["infrastructure", "aws", "deployment"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Infrastructure Issue
        
        Use this template to report issues with:
        - AWS Lambda functions
        - S3 deployment and hosting
        - API Gateway
        - CloudFront distribution
        - CI/CD pipelines
        - Environment configuration
        - Performance and scaling issues

  - type: dropdown
    id: infrastructure_type
    attributes:
      label: Infrastructure Type
      description: What type of infrastructure issue is this?
      options:
        - AWS Lambda Function
        - S3 Bucket/Deployment
        - API Gateway
        - CloudFront Distribution
        - CI/CD Pipeline
        - Environment Configuration
        - Performance/Scaling
        - Security/Compliance
        - Monitoring/Logging
        - Database/Storage
        - Network/Connectivity
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this infrastructure issue?
      options:
        - Critical - Service down, data loss, security breach
        - High - Major functionality affected, partial outage
        - Medium - Minor functionality affected, degraded performance
        - Low - Cosmetic issue, minor inconvenience
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment is affected?
      options:
        - Production
        - Staging
        - Development
        - All Environments
        - Local Development
    validations:
      required: true

  - type: input
    id: aws_region
    attributes:
      label: AWS Region
      description: Which AWS region is affected?
      placeholder: "ap-south-1, us-east-1, eu-west-1"
    validations:
      required: false

  - type: input
    id: issue_title
    attributes:
      label: Brief Description
      description: Provide a concise summary of the infrastructure issue
      placeholder: "Lambda function timeout causing API failures"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the infrastructure issue
      placeholder: |
        ## What happened?
        Describe the infrastructure issue in detail...
        
        ## What did you expect to happen?
        Describe what you expected to happen instead...
        
        ## Impact
        Describe the impact on users, services, or business...
        
        ## Timeline
        When did this issue start? Is it ongoing?
    validations:
      required: true

  - type: textarea
    id: affected_services
    attributes:
      label: Affected Services
      description: List all services and components affected
      placeholder: |
        ## AWS Services Affected
        - Lambda Function: [function name]
        - API Gateway: [endpoint/route]
        - S3 Bucket: [bucket name]
        - CloudFront: [distribution ID]
        - Other services: [list]
        
        ## Application Components Affected
        - Frontend: [specific pages/components]
        - Backend APIs: [specific endpoints]
        - Database: [specific tables/queries]
        - External integrations: [list]
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: Error Messages and Logs
      description: Include relevant error messages, logs, and monitoring alerts
      placeholder: |
        ## CloudWatch Logs
        ```
        [ERROR] Lambda function timeout after 30 seconds
        [ERROR] API Gateway 504 Gateway Timeout
        [ERROR] S3 bucket access denied
        ```
        
        ## Application Logs
        ```
        [ERROR] Failed to fetch data from API
        [ERROR] Authentication token expired
        [ERROR] Database connection failed
        ```
        
        ## Monitoring Alerts
        - CloudWatch Alarm: [alarm name]
        - Custom Metric: [metric name]
        - Third-party monitoring: [service name]
    validations:
      required: false

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: If applicable, provide steps to reproduce the issue
      placeholder: |
        ## Steps to Reproduce
        
        1. Navigate to [specific page/endpoint]
        2. Perform [specific action]
        3. Observe [specific error/behavior]
        
        ## Trigger Conditions
        
        - Time-based: [specific times]
        - Load-based: [specific conditions]
        - User-based: [specific user types]
        - Data-based: [specific data conditions]
    validations:
      required: false

  - type: textarea
    id: current_configuration
    attributes:
      label: Current Configuration
      description: Include relevant configuration details
      placeholder: |
        ## AWS Configuration
        
        ### Lambda Function
        - Function name: [name]
        - Runtime: [runtime]
        - Memory: [memory]
        - Timeout: [timeout]
        - Environment variables: [list]
        
        ### S3 Configuration
        - Bucket name: [name]
        - Region: [region]
        - CORS configuration: [details]
        - Bucket policy: [details]
        
        ### API Gateway
        - API name: [name]
        - Endpoint: [endpoint]
        - Authentication: [type]
        - Rate limiting: [details]
        
        ### CloudFront
        - Distribution ID: [ID]
        - Origin: [origin]
        - Cache behavior: [details]
    validations:
      required: false

  - type: textarea
    id: monitoring_metrics
    attributes:
      label: Monitoring and Metrics
      description: Include relevant monitoring data and metrics
      placeholder: |
        ## Performance Metrics
        
        ### Lambda Metrics
        - Invocation count: [number]
        - Duration: [average/max]
        - Error rate: [percentage]
        - Throttles: [number]
        
        ### API Gateway Metrics
        - Request count: [number]
        - 4xx errors: [number]
        - 5xx errors: [number]
        - Latency: [average]
        
        ### S3 Metrics
        - Request count: [number]
        - Error rate: [percentage]
        - Data transfer: [amount]
        
        ### CloudFront Metrics
        - Request count: [number]
        - Cache hit ratio: [percentage]
        - Error rate: [percentage]
    validations:
      required: false

  - type: textarea
    id: recent_changes
    attributes:
      label: Recent Changes
      description: Describe any recent changes that might have caused this issue
      placeholder: |
        ## Recent Changes
        
        ### Deployments
        - Date: [date]
        - Changes: [description]
        - Impact: [description]
        
        ### Configuration Changes
        - Date: [date]
        - Changes: [description]
        - Impact: [description]
        
        ### Infrastructure Changes
        - Date: [date]
        - Changes: [description]
        - Impact: [description]
        
        ### Third-party Changes
        - Service: [service name]
        - Changes: [description]
        - Impact: [description]
    validations:
      required: false

  - type: textarea
    id: troubleshooting_steps
    attributes:
      label: Troubleshooting Steps Taken
      description: Describe any troubleshooting steps already taken
      placeholder: |
        ## Troubleshooting Steps
        
        ### Steps Taken
        1. [Step 1]: [Result]
        2. [Step 2]: [Result]
        3. [Step 3]: [Result]
        
        ### Commands Executed
        ```bash
        # Example commands
        aws lambda get-function --function-name [name]
        aws logs describe-log-groups --log-group-name-prefix [prefix]
        aws cloudwatch get-metric-statistics --namespace [namespace]
        ```
        
        ### Manual Tests
        - [Test 1]: [Result]
        - [Test 2]: [Result]
        - [Test 3]: [Result]
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution (Optional)
      description: If you have ideas for how to fix this issue, describe them here
      placeholder: |
        ## Proposed Solution
        
        ### Immediate Actions
        - [Action 1]: [description]
        - [Action 2]: [description]
        - [Action 3]: [description]
        
        ### Long-term Fixes
        - [Fix 1]: [description]
        - [Fix 2]: [description]
        - [Fix 3]: [description]
        
        ### Prevention Measures
        - [Measure 1]: [description]
        - [Measure 2]: [description]
        - [Measure 3]: [description]
    validations:
      required: false

  - type: checkboxes
    id: infrastructure_characteristics
    attributes:
      label: Issue Characteristics
      description: Check any items that apply to this infrastructure issue
      options:
        - label: This issue affects production environment
        - label: This issue affects multiple services
        - label: This issue is related to recent deployment
        - label: This issue is related to configuration changes
        - label: This issue is related to scaling/performance
        - label: This issue is related to security/compliance
        - label: This issue is related to monitoring/alerting
        - label: This issue is related to cost optimization
        - label: This issue is related to third-party services
        - label: This issue is related to data/storage
        - label: This issue is related to network/connectivity
        - label: This issue requires immediate attention

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Link any related issues or pull requests
      placeholder: "Related to #123, Caused by #456, Blocks #789"
    validations:
      required: false

  - type: input
    id: labels
    attributes:
      label: Additional Labels
      description: Add any additional labels that might be relevant
      placeholder: "lambda, s3, api-gateway, cloudfront, monitoring, etc."
    validations:
      required: false