name: Security Issue
description: Report security vulnerabilities or concerns in the EFY Frontend platform
title: "[SECURITY] "
labels: ["security", "vulnerability"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Security Issue
        
        **⚠️ IMPORTANT: For critical security vulnerabilities, please use our private security reporting process instead of creating a public issue.**
        
        Use this template to report:
        - Security vulnerabilities
        - Authentication/authorization issues
        - Data privacy concerns
        - AWS security configuration issues
        - API security concerns
        - Third-party security issues

  - type: dropdown
    id: security_type
    attributes:
      label: Security Type
      description: What type of security issue is this?
      options:
        - Authentication Vulnerability
        - Authorization Vulnerability
        - Data Exposure/Privacy
        - AWS Security Configuration
        - API Security Issue
        - Frontend Security Issue
        - Third-party Security Issue
        - Infrastructure Security
        - Code Security Issue
        - Network Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this security issue?
      options:
        - Critical - Immediate action required, data breach, system compromise
        - High - Significant security risk, potential data exposure
        - Medium - Moderate security risk, limited impact
        - Low - Minor security concern, informational
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment is affected?
      options:
        - Production
        - Staging
        - Development
        - All Environments
        - Local Development
    validations:
      required: true

  - type: input
    id: issue_title
    attributes:
      label: Brief Description
      description: Provide a concise summary of the security issue
      placeholder: "JWT tokens not properly validated in API calls"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the security issue
      placeholder: |
        ## What is the security issue?
        Describe the security vulnerability or concern in detail...
        
        ## What is the potential impact?
        Describe the potential impact on users, data, or systems...
        
        ## How was this discovered?
        Describe how this security issue was found...
        
        ## Timeline
        When was this issue discovered? Is it currently being exploited?
    validations:
      required: true

  - type: textarea
    id: vulnerability_details
    attributes:
      label: Vulnerability Details
      description: Provide technical details about the vulnerability
      placeholder: |
        ## Technical Details
        
        ### Vulnerability Type
        - [Type of vulnerability]
        - [Specific technical details]
        
        ### Affected Components
        - Frontend: [specific components/pages]
        - Backend: [specific APIs/functions]
        - Infrastructure: [specific AWS services]
        - Third-party: [specific services]
        
        ### Attack Vector
        - [How the vulnerability could be exploited]
        - [Prerequisites for exploitation]
        - [Potential attack scenarios]
        
        ### Proof of Concept
        - [Steps to reproduce the vulnerability]
        - [Code examples if applicable]
        - [Tools or methods used]
    validations:
      required: true

  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: Assess the potential impact of this security issue
      placeholder: |
        ## Impact Assessment
        
        ### Data Impact
        - [What data could be exposed?]
        - [How sensitive is the data?]
        - [How many users could be affected?]
        
        ### System Impact
        - [What systems could be compromised?]
        - [What functionality could be affected?]
        - [What AWS resources could be at risk?]
        
        ### Business Impact
        - [What are the business implications?]
        - [What are the compliance implications?]
        - [What are the reputational risks?]
        
        ### User Impact
        - [How could users be affected?]
        - [What user data could be compromised?]
        - [What user actions could be affected?]
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps to reproduce the security issue
      placeholder: |
        ## Steps to Reproduce
        
        1. [Step 1]
        2. [Step 2]
        3. [Step 3]
        4. [Observe the security issue]
        
        ## Prerequisites
        
        - [Required access level]
        - [Required user role]
        - [Required data or conditions]
        - [Required tools or knowledge]
        
        ## Example Payload/Request
        
        ```json
        {
          "example": "payload"
        }
        ```
    validations:
      required: true

  - type: textarea
    id: current_mitigations
    attributes:
      label: Current Mitigations
      description: Describe any current security measures or mitigations
      placeholder: |
        ## Current Security Measures
        
        ### Authentication
        - [Current authentication method]
        - [Current authorization checks]
        - [Current session management]
        
        ### Data Protection
        - [Current data encryption]
        - [Current data validation]
        - [Current access controls]
        
        ### Infrastructure Security
        - [Current AWS security configuration]
        - [Current network security]
        - [Current monitoring/alerting]
        
        ### Application Security
        - [Current input validation]
        - [Current output encoding]
        - [Current error handling]
    validations:
      required: false

  - type: textarea
    id: proposed_fixes
    attributes:
      label: Proposed Fixes
      description: Suggest potential fixes or mitigation strategies
      placeholder: |
        ## Proposed Fixes
        
        ### Immediate Actions
        - [Action 1]: [description and timeline]
        - [Action 2]: [description and timeline]
        - [Action 3]: [description and timeline]
        
        ### Long-term Solutions
        - [Solution 1]: [description and timeline]
        - [Solution 2]: [description and timeline]
        - [Solution 3]: [description and timeline]
        
        ### Prevention Measures
        - [Measure 1]: [description]
        - [Measure 2]: [description]
        - [Measure 3]: [description]
        
        ### Monitoring Improvements
        - [Monitoring 1]: [description]
        - [Monitoring 2]: [description]
        - [Monitoring 3]: [description]
    validations:
      required: false

  - type: textarea
    id: compliance_implications
    attributes:
      label: Compliance Implications
      description: Describe any compliance or regulatory implications
      placeholder: |
        ## Compliance Implications
        
        ### Data Protection Regulations
        - [GDPR implications]
        - [CCPA implications]
        - [Other relevant regulations]
        
        ### Industry Standards
        - [ISO 27001 implications]
        - [SOC 2 implications]
        - [Other relevant standards]
        
        ### Internal Policies
        - [Internal security policies]
        - [Data handling policies]
        - [Access control policies]
    validations:
      required: false

  - type: textarea
    id: disclosure_timeline
    attributes:
      label: Disclosure Timeline
      description: Describe the timeline for disclosure and remediation
      placeholder: |
        ## Disclosure Timeline
        
        ### Discovery
        - Date discovered: [date]
        - Discovered by: [name/team]
        - Method of discovery: [method]
        
        ### Reporting
        - Date reported: [date]
        - Reported to: [team/person]
        - Reporting method: [method]
        
        ### Remediation
        - Target fix date: [date]
        - Responsible team: [team]
        - Verification method: [method]
        
        ### Public Disclosure
        - Planned disclosure date: [date]
        - Disclosure method: [method]
        - Responsible party: [person/team]
    validations:
      required: false

  - type: checkboxes
    id: security_characteristics
    attributes:
      label: Security Characteristics
      description: Check any items that apply to this security issue
      options:
        - label: This issue affects production environment
        - label: This issue involves data exposure
        - label: This issue involves authentication bypass
        - label: This issue involves authorization bypass
        - label: This issue involves AWS security configuration
        - label: This issue involves API security
        - label: This issue involves frontend security
        - label: This issue involves third-party services
        - label: This issue requires immediate attention
        - label: This issue affects user privacy
        - label: This issue involves compliance violations
        - label: This issue requires external disclosure

  - type: input
    id: responsible_disclosure
    attributes:
      label: Responsible Disclosure
      description: Are you reporting this as part of responsible disclosure?
      placeholder: "Yes/No - If yes, please provide your contact information"
    validations:
      required: false

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Link any related issues or pull requests
      placeholder: "Related to #123, Similar to #456, Follow-up to #789"
    validations:
      required: false

  - type: input
    id: labels
    attributes:
      label: Additional Labels
      description: Add any additional labels that might be relevant
      placeholder: "authentication, authorization, data-privacy, aws-security, etc."
    validations:
      required: false